## The file responsible for gitlab continuous integration ##

before_script:
  - apt install python3-pip
  - pip3 install setuptools


stages:
  - test

test:
  stage: test
  script:
    - python setup.py runTests