## The file responsible for gitlab continuous integration ##

image: python:3.4

before_script:
  - pip install requests
  - pip install Django
  - pip install pytest
  - pip install model_mommy

stages:
  - test

test:
  stage: test
  script:
    - python setup.py runTest
